/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bankingapp;

import org.sqlite.SQLiteDataSource;
import java.sql.*;
import java.util.Scanner;

public class App {
    static Scanner input = new Scanner(System.in);
    static SQLiteDataSource dataSource = new SQLiteDataSource();

    /**
     * Main method
     *
     * @param args
     */
    public static void main(String[] args) {
        //String url set as program parameter
        dataSource.setUrl(args[0]);

        //Connect to the database
        try (Connection connection = dataSource.getConnection()) {
            try (Statement statement = connection.createStatement()) {

                //Create DB
                DBTrans db = new DBTrans();
                db.createDB(statement);

                //Initialize response and create Map object
                int response = -1;                

                do {
                    System.out.println("\n1. Create an account\n" +
                            "2. Log into account\n" +
                            "0. Exit");

                    response = input.nextInt();
                    switch (response) {
                        case 1:
                            System.out.println(new CreateAccount(connection));
                            break;
                        case 2:
                            System.out.println(new LogIn(connection));
                    }
                } while (response != 0);

                System.out.println("\nBye!");

                //Close the Statement Object
            } catch (SQLException e) {
                e.printStackTrace();
            }

            //Close the Connection object
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
